"""control submissions

Revision ID: 176c3b74a595
Revises: 9635daf8cc3a
Create Date: 2024-07-04 15:12:26.211405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176c3b74a595'
down_revision = '9635daf8cc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_users_can_submit_benchmarks', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('_db_users_can_submit_tools', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('_db_users_can_submit_tools')
        batch_op.drop_column('_db_users_can_submit_benchmarks')

    # ### end Alembic commands ###
