"""Assign static eni

Revision ID: 292e90b0cc7d
Revises: c2e671eb2b9b
Create Date: 2024-07-09 14:31:23.866893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292e90b0cc7d'
down_revision = 'c2e671eb2b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flasklogin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eni', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mac', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flasklogin_users', schema=None) as batch_op:
        batch_op.drop_column('mac')
        batch_op.drop_column('eni')

    # ### end Alembic commands ###
