"""Safe config file location and content

Revision ID: 456d05c3a43c
Revises: 176c3b74a595
Create Date: 2024-07-05 20:37:37.658766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456d05c3a43c'
down_revision = '176c3b74a595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_yaml_config_file', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('_db_yaml_config_content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.drop_column('_db_yaml_config_content')
        batch_op.drop_column('_db_yaml_config_file')

    # ### end Alembic commands ###
