"""Safe which networks to run

Revision ID: 5a3e1aaecba8
Revises: 456d05c3a43c
Create Date: 2024-07-05 20:59:36.195706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3e1aaecba8'
down_revision = '456d05c3a43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_run_networks', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.drop_column('_db_run_networks')

    # ### end Alembic commands ###
