"""Added option to not shut down instances at job end

Revision ID: 5c077db00e6f
Revises: 5a3e1aaecba8
Create Date: 2024-07-07 17:30:10.382169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c077db00e6f'
down_revision = '5a3e1aaecba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_aws_terminate_at_end', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('_db_aws_terminate_at_end')

    # ### end Alembic commands ###
