"""Support restart after postinstall

Revision ID: 6b52f9be9ee3
Revises: bdc8ea60b5de
Create Date: 2024-07-12 12:37:49.300529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b52f9be9ee3'
down_revision = 'bdc8ea60b5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_restart_after_postinstallation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toolkit_tasks', schema=None) as batch_op:
        batch_op.drop_column('_db_restart_after_postinstallation')

    # ### end Alembic commands ###
