"""empty message

Revision ID: 9635daf8cc3a
Revises: d718c4320088
Create Date: 2024-07-04 08:57:48.052190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9635daf8cc3a'
down_revision = 'd718c4320088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_allow_non_admin_login', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('_db_allow_non_admin_login')

    # ### end Alembic commands ###
