"""store settings in db

Revision ID: b7115fa53b10
Revises: 0decc2b25eed
Create Date: 2024-07-03 13:20:40.806416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7115fa53b10'
down_revision = '0decc2b25eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('_db_id', sa.Integer(), nullable=False),
    sa.Column('_db_aws_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('_db_id', name=op.f('pk_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
