"""Make instance timeout configurable

Revision ID: c2e671eb2b9b
Revises: 5c077db00e6f
Create Date: 2024-07-08 10:35:39.744010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e671eb2b9b'
down_revision = '5c077db00e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_instance_timeout', sa.Integer(), server_default=sa.text('4'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('_db_instance_timeout')

    # ### end Alembic commands ###
