"""empty message

Revision ID: d718c4320088
Revises: b7115fa53b10
Create Date: 2024-07-03 15:42:56.680151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd718c4320088'
down_revision = 'b7115fa53b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_db_aws_terminate_on_failure', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('_db_aws_terminate_on_failure')

    # ### end Alembic commands ###
