#!/bin/bash

i=0
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 ; do
    case $(($i % 4)) in
        0 ) j="-" ;;
        1 ) j="\\" ;;
        2 ) j="|" ;;
        3 ) j="/" ;;
    esac
    echo "[$j] Waiting for other software managers to finish..." 
    sleep 60
    ((i=i+1))
done 

/usr/bin/apt-get "$@"
